{
 "title": "Compute Instances",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_name",
    "query": {
     "query": "label_values(vm_vcpu_milliseconds_total{projectId=\"${__user.login}\"},instanceName)"
    }
   },
   { "name": "data_source", "query": "prometheus" },
   { "name": "project_id", "label": "project ID", "query": "${__user.login}" }
  ]
 },
 "panels": [
  { "title": "Instance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(irate(vm_vcpu_milliseconds_total{instanceName=~\"$instance_name\",projectId=\"$project_id\"}[2m])) by (instanceName,uuid) / 10) or (avg(irate(vm_vcpu_milliseconds_total{uuid=~\"$instance_uuid\",projectId=\"$project_id\"}[2m])) by (instanceName,uuid) / 10)",
     "legendFormat": "{{instanceName}} ({{uuid}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vm_memory_maximum_bytes{instanceName=~\"$instance_name\",projectId=\"$project_id\"} or vm_memory_maximum_bytes{uuid=~\"$instance_uuid\",projectId=\"$project_id\"}",
     "legendFormat": "Max: {{instanceName}} ({{uuid}})"
    },
    {
     "expr": "vm_memory_maximum_bytes{instanceName=~\"$instance_name\",projectId=\"$project_id\"} - vm_memory_usable{instanceName=~\"$instance_name\",projectId=\"$project_id\"} or vm_memory_maximum_bytes{uuid=~\"$instance_uuid\",projectId=\"$project_id\"} - vm_memory_usable{uuid=~\"$instance_uuid\",projectId=\"$project_id\"}",
     "legendFormat": "Used: {{instanceName}} ({{uuid}})"
    }
   ]
  },
  {
   "title": "Network Bits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(vm_network_receive_bytes_total{instanceName=~\"$instance_name\",interface=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_network_receive_bytes_total{uuid=~\"$instance_uuid\",interface=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Ingress: {{instanceName}} ({{uuid}})"
    },
    {
     "expr": "irate(vm_network_transmit_bytes_total{instanceName=~\"$instance_name\",interface=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_network_transmit_bytes_total{uuid=~\"$instance_uuid\",interface=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Egress: {{instanceName}} ({{uuid}})"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(vm_network_receive_packets_total{instanceName=~\"$instance_name\",interface=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_network_receive_packets_total{uuid=~\"$instance_uuid\",interface=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Ingress: {{instanceName}} ({{uuid}})"
    },
    {
     "expr": "irate(vm_network_transmit_packets_total{instanceName=~\"$instance_name\",interface=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_network_transmit_packets_total{uuid=~\"$instance_uuid\",interface=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Egress: {{instanceName}} ({{uuid}})"
    }
   ]
  },
  {
   "title": "Disk Bytes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(vm_disk_write_bytes_total{instanceName=~\"$instance_name\",device=~\".*\"}[2m]) or irate(vm_disk_write_bytes_total{uuid=~\"$instance_uuid\",device=~\".*\"}[2m])",
     "legendFormat": "Write: {{instanceName}} ({{uuid}}) [{{device}}]"
    },
    {
     "expr": "irate(vm_disk_read_bytes_total{instanceName=~\"$instance_name\",device=~\".*\"}[2m]) or irate(vm_disk_read_bytes_total{uuid=~\"$instance_uuid\",device=~\".*\"}[2m]) ",
     "legendFormat": "Read: {{instanceName}} ({{uuid}}) [{{device}}]"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vm_disk_write_requests_total{instanceName=~\"$instance_name\",device=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_disk_write_requests_total{uuid=~\"$instance_uuid\",device=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Write IOPS: {{instanceName}} ({{uuid}}) [{{device}}]"
    },
    {
     "expr": "irate(vm_disk_read_requests_total{instanceName=~\"$instance_name\",device=~\".*\",projectId=\"$project_id\"}[2m]) or irate(vm_disk_read_requests_total{uuid=~\"$instance_uuid\",device=~\".*\",projectId=\"$project_id\"}[2m])",
     "legendFormat": "Read IOPS: {{instanceName}} ({{uuid}}) [{{device}}]"
    }
   ]
  }
 ]
}