{
 "title": "ING - Instance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "customer_project_id", "label": "Project ID", "query": "${__user.login}" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(node_pfsense_interface_up{ing_customer_project_id=\"$customer_project_id\"},ing_service_name)"
    }
   },
   { "name": "if_wan_name", "label": "Interface WAN Name", "query": "WAN" }
  ]
 },
 "panels": [
  {
   "title": "Current connections",
   "type": "timeseries",
   "description": "monitor the number of active connections currently passing through your pfSense firewall and Max Connections = 4,000,000",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pfsense_pf_states_current{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Active Connections: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "New connections",
   "type": "timeseries",
   "description": "New connection rate over a 5-minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ing_service_name, device) (\r\n  round(increase(pfsense_pf_states_inserts_total{job=\"$job\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\", device=\"vtnet0\"}[5m]))\r\n)",
     "legendFormat": "Connection Drop: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Total Packet Drop (IN/OUT 5m)",
   "type": "timeseries",
   "description": "Incoming packet drop rate on WAN, measured over a 5-minute interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m])",
     "legendFormat": "Inbound: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m])",
     "legendFormat": "Outbound: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Total Bandwidth (IN/OUT 5m)",
   "type": "timeseries",
   "description": "Current Incoming Throughput (Download Speed) and Throughput (Upload Speed)  in bits per second (bps).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]) * 8",
     "legendFormat": "Inbound: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]) * 8",
     "legendFormat": "Outbound: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Totals Packets (IN/OUT 5m)",
   "type": "timeseries",
   "description": "Packages of Incoming Packets and Outboud Packets on the WAN interface over a 5-minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ing_service_name, device) (increase(node_network_receive_packets_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inbound: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "sum by (ing_service_name, device) (increase(node_network_transmit_packets_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Outbound: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "State Table (%)",
   "type": "timeseries",
   "description": "Percentage of State Table Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (ing_service_name, device) (pfsense_pf_states_current{job=\"$job\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\", device=\"vtnet0\"}) / 400000) * 100",
     "legendFormat": "State Table: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Total Interface Discard (IN/OUT 5m)",
   "type": "timeseries",
   "description": "Drop of Network Issues (Discards) on the WAN interface over a 5-minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pfsense_interface_discards_in_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Inbound: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "pfsense_interface_discards_out_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Outbound: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Total Interface Errors (IN/OUT 5m)",
   "type": "timeseries",
   "description": "Counter metric that tracks the cumulative number of corrupted or invalid packets received by a specific network interface since the system started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pfsense_interface_errors_in_total{device=\"vtnet0\", job=\"$job\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Interface Inbound Errors: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "pfsense_interface_errors_out_total{device=\"vtnet0\", job=\"$job\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Interface Outbound Errors: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "Total Packet Loss (%)",
   "type": "timeseries",
   "description": "percentage of packet loss on a specific gateway",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "pfsense_gateway_loss_percent{job=\"$job\", gw_name=\"WAN_DHCP\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}",
     "legendFormat": "Gateway Loss: {{ing_service_name}} [{{gw_name}}]"
    }
   ]
  },
  {
   "title": "Inbound/Outbound Public Network Packets (5m)",
   "type": "timeseries",
   "description": "Incoming Packets and Outbound Packets on the WAN interface over a 5-minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (ing_service_name, device) (increase(node_network_receive_packets_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Inbound: {{ing_service_name}} [{{device}}]"
    },
    {
     "expr": "sum by (ing_service_name, device) (increase(node_network_transmit_packets_total{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Outbound: {{ing_service_name}} [{{device}}]"
    }
   ]
  },
  {
   "title": "External Network Latency (Target Sites)",
   "type": "timeseries",
   "description": "The round-trip time (RTT) in milliseconds between your pfSense firewall and specific targets, including domestic and international IPs or domains",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (ing_service_name, device, target) (\n  pfsense_custom_ping_latency_ms{job=\"$job\", device=\"vtnet0\", ing_customer_project_id=\"$customer_project_id\", ing_service_name=~\"$service_name\"}\n)",
     "legendFormat": "Ping Latency: {{ing_service_name}} [{{device}}] - {{target}}"
    }
   ]
  }
 ]
}