{
 "title": "Objects Storage",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket_name",
    "label": "bucket name",
    "query": {
     "query": "label_values(radosgw_usage_bucket_bytes{owner=\"${__user.login}\"},bucket)"
    }
   },
   { "name": "project_id", "label": "ProjectID", "query": "${__user.login}" },
   {
    "name": "availability_zone",
    "label": "availability zone",
    "query": {
     "query": "label_values(radosgw_usage_bucket_bytes{owner=\"${__user.login}\"},cluster)"
    }
   },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radosgw_usage_bucket_bytes{bucket=~\"$bucket_name\", cluster=~\"$availability_zone\",owner=\"$project_id\"}",
     "legendFormat": "{{bucket}} {{cluster}}"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(bucket,cluster)(radosgw_usage_received_bytes_total{bucket=~\"$bucket_name\", cluster=~\"$availability_zone\",owner=\"$project_id\"})",
     "legendFormat": "Ingress {{bucket}} {{cluster}}"
    },
    {
     "expr": "sum by(bucket,cluster)(radosgw_usage_sent_bytes_total{bucket=~\"$bucket_name\", cluster=~\"$availability_zone\",owner=\"$project_id\"})",
     "legendFormat": "Egress {{bucket}} {{cluster}}"
    }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (bucket, cluster) (radosgw_usage_ops_total{bucket=~\"$bucket_name\", cluster=~\"$availability_zone\",category=~\"bulk_upload|complete_multipart|config_bucket_meta_search|copy_obj|create_bucket|init_multipart|list_bucket|list_bucket_multiparts|list_buckets|list_multipart|multi_object_delete|post_obj|put_account_metadata|put_acls|put_bucket_encryption|put_bucket_logging|put_bucket_metadata|put_bucket_object_lock|put_bucket_policy|put_bucket_replication|put_bucket_tags|put_cors|put_lifecycle|put_obj|put_obj_legal_hold|put_obj_metadata|put_obj_retention|put_obj_tags|set_attrs|set_bucket_versioning|set_bucket_website|set_request_payment|stat_account|stat_bucket\",owner=\"$project_id\"})",
     "legendFormat": "PUT, COPY, POST, LIST {{bucket}} {{cluster}}"
    },
    {
     "expr": "sum by (bucket, cluster) (radosgw_usage_ops_total{bucket=~\"$bucket_name\", cluster=~\"$availability_zone\",category!~\"bulk_upload|complete_multipart|config_bucket_meta_search|copy_obj|create_bucket|init_multipart|list_bucket|list_bucket_multiparts|list_buckets|list_multipart|multi_object_delete|post_obj|put_account_metadata|put_acls|put_bucket_encryption|put_bucket_logging|put_bucket_metadata|put_bucket_object_lock|put_bucket_policy|put_bucket_replication|put_bucket_tags|put_cors|put_lifecycle|put_obj|put_obj_legal_hold|put_obj_metadata|put_obj_retention|put_obj_tags|set_attrs|set_bucket_versioning|set_bucket_website|set_request_payment|stat_account|stat_bucket\",owner=\"$project_id\"})",
     "legendFormat": "GET, SELECT, Other {{bucket}} {{cluster}}"
    }
   ]
  }
 ]
}